/* Generated By:JJTree: Do not edit this line. ASTLiteral.java */

/****************************************************************************
 *
 * Copyright (C) 2004. The MITRE Corporation (http://www.mitre.org/). All Rights Reserved.
 * Consult the LICENSE file in the root of the distribution for terms and restrictions.
 *
 *       Release: 1.0
 *       Date: 24-August-2004
 *       Author: Carl Burke
 *
 *****************************************************************************/
package org.mitre.midiki.compiler.parser;

public class ASTLiteral extends SimpleNode {
    static public final int br_int = 1;
    static public final int br_flt = 2;
    static public final int br_chr = 3;
    static public final int br_str = 4;
    private int branch;
    public void setBranch(int b)
    {
        branch = b;
    }
    public int getBranch()
    {
        return branch;
    }

  public ASTLiteral(int id) {
    super(id);
  }

  public ASTLiteral(MKParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MKParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
