/* Generated By:JJTree: Do not edit this line. MKParserVisitor.java */

/****************************************************************************
 *
 * Copyright (C) 2004. The MITRE Corporation (http://www.mitre.org/). All Rights Reserved.
 * Consult the LICENSE file in the root of the distribution for terms and restrictions.
 *
 *       Release: 1.0
 *       Date: 24-August-2004
 *       Author: Carl Burke
 *
 *****************************************************************************/
package org.mitre.midiki.compiler.parser;

public interface MKParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTCompilationUnit node, Object data);
  public Object visit(ASTName node, Object data);
  public Object visit(ASTDesignator node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTVariable node, Object data);
  public Object visit(ASTQualifierList node, Object data);
  public Object visit(ASTDotQualifier node, Object data);
  public Object visit(ASTHashQualifier node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTAssignmentOperator node, Object data);
  public Object visit(ASTLogicalExpression node, Object data);
  public Object visit(ASTLogicalOperator node, Object data);
  public Object visit(ASTRelationalExpression node, Object data);
  public Object visit(ASTRelationalOperator node, Object data);
  public Object visit(ASTAdditiveExpression node, Object data);
  public Object visit(ASTAdditiveOperator node, Object data);
  public Object visit(ASTMultiplicativeExpression node, Object data);
  public Object visit(ASTMultiplicativeOperator node, Object data);
  public Object visit(ASTUnaryExpression node, Object data);
  public Object visit(ASTNegationOperator node, Object data);
  public Object visit(ASTPrimaryExpression node, Object data);
  public Object visit(ASTLiteral node, Object data);
  public Object visit(ASTIntegerLiteral node, Object data);
  public Object visit(ASTFloatingPointLiteral node, Object data);
  public Object visit(ASTCharacterLiteral node, Object data);
  public Object visit(ASTStringLiteral node, Object data);
  public Object visit(ASTArguments node, Object data);
  public Object visit(ASTArgumentList node, Object data);
  public Object visit(ASTExpressions node, Object data);
  public Object visit(ASTExpressionList node, Object data);
  public Object visit(ASTStatements node, Object data);
  public Object visit(ASTStatementList node, Object data);
  public Object visit(ASTStatement node, Object data);
}
