/* Generated By:JJTree&JavaCC: Do not edit this line. MKParserConstants.java */

/****************************************************************************
 *
 * Copyright (C) 2004. The MITRE Corporation (http://www.mitre.org/). All Rights Reserved.
 * Consult the LICENSE file in the root of the distribution for terms and restrictions.
 *
 *       Release: 1.0
 *       Date: 24-August-2004
 *       Author: Carl Burke
 *
 *****************************************************************************/
package org.mitre.midiki.compiler.parser;

public interface MKParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int MULTI_LINE_COMMENT = 10;
  int INTEGER_LITERAL = 12;
  int DECIMAL_LITERAL = 13;
  int HEX_LITERAL = 14;
  int OCTAL_LITERAL = 15;
  int FLOATING_POINT_LITERAL = 16;
  int EXPONENT = 17;
  int CHARACTER_LITERAL = 18;
  int STRING_LITERAL = 19;
  int IDENTIFIER = 20;
  int VARIABLE = 21;
  int LC_LETTER = 22;
  int UC_LETTER = 23;
  int DIGIT = 24;
  int LPAREN = 25;
  int RPAREN = 26;
  int LBRACE = 27;
  int RBRACE = 28;
  int LBRACKET = 29;
  int RBRACKET = 30;
  int SEMICOLON = 31;
  int COMMA = 32;
  int DOT = 33;
  int HASH = 34;
  int FLEX = 35;
  int GT = 36;
  int LT = 37;
  int EQ = 38;
  int LE = 39;
  int GE = 40;
  int NE = 41;
  int SC_OR = 42;
  int SC_AND = 43;
  int BANG = 44;
  int PLUS = 45;
  int MINUS = 46;
  int STAR = 47;
  int SLASH = 48;
  int SYMBOL = 49;
  int SYMBOL_CHAR = 50;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "\"%\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 11>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<VARIABLE>",
    "<LC_LETTER>",
    "<UC_LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"#\"",
    "\"^\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<SYMBOL>",
    "<SYMBOL_CHAR>",
    "\"|\"",
  };

}
